application: strava-raceways
version: 1
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)(README|CONTRIBUTING|Readme).md$
- ^(.*/)Makefile.md$
- ^(.*/)(README|LICENSE|CONTRIBUTING|AUTHORS|PATENTS|COPYING)$
- ^node_modules/.*$

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# yeoman stuff
- url: /styles
  static_dir: app/styles
- url: /images
  static_dir: app/images
- url: /components
  static_dir: app/components
- url: /scripts
  static_dir: app/scripts
- url: /bower_components
  static_dir: app/bower_components
- url: /elements
  static_dir: app/elements
- url: /index
  static_files: app/index.html
  upload: app/index\.html
- url: /404
  static_files: app/404.html
  upload: app/404\.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
